# Project information
site_name: AuroraOlian's Notebook
site_author: AuroraOlian
site_url: https://auroraolian.github.io
site_description: Sharing my notes and thoughts on computer science and technology.

# Repository
repo_name: AuroraOlian.github.io
repo_url: https://github.com/AuroraOlian/AuroraOlian.github.io
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 <a href="https://github.com/AuroraOlian/AuroraOlian.github.io" target="_blank" rel="noopener">Aurora Olian</a>

# Configuration
theme:
  name: material
  language: en
  # custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-5
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-3
        name: Switch to system preference
  icon:
    logo: octicons/paper-airplane-16
    repo: fontawesome/brands/github-alt
    admonition:
      info: fontawesome/solid/anchor
      note: fontawesome/solid/pen-nib
      abstract: fontawesome/solid/list
      tip: fontawesome/solid/lightbulb
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: material/alien
      danger: fontawesome/solid/virus
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/link
  font:
    text: 'LXGW WenKai Screen R'
    code: JetBrains Mono
  favicon: img/favicon.ico

plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - minify:
  #     minify_html: true
  # - statistics:
  # words_per_minute: 200
  # - git-revision-date-localized:
  #     type: datetime
  #     timezone: Asia/Shanghai
  #     locale: zh
  #     enable_creation_date: true
  #     exclude:
  #       - index.md
  # - coming.md
  # - link.md
  # - tech_accu/index.md
  # - cour_note/index.md
  # - pape_read/index.md
  # - others/index.md
  # - tags:
  #     tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
  #       kwds:
  #         case: lower

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AuroraOlian/
extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
extra_javascript:
  - javascripts/shortcuts.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

markdown_extensions:
  - admonition
  # Annotations
  - attr_list # Annotations, Buttons, Icons, Emojis
  - md_in_html
  - pymdownx.superfences # Annotations, Code blocks
  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      check_paths: true
      url_download: false
      url_max_size: 33554432
      url_timeout: 10
  - pymdownx.details
  # Content tabs
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  # Data tables
  - tables
  # Diagrams
  # Footnotes
  - footnotes
  # Formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # Icons, Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # Lists

  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Core curriculum:
      - Fundamentals of Data Structure:
          - fds.md
      - Discrete Mathematics and Its Application:
          - dm/index.md
          - dm/1.md
          - dm/2.md
          - dm/3.md
          - dm/4.md
          - dm/5.md
          - dm/6.md
          - dm/8.md
          - dm/9.md
          - dm/10.md
          - dm/11.md
  - Distributed System:
      - Basic Theorem: ds/distributed_system.md
      - GFS: ds/GFS.md
      - MapReduce: ds/MapReduce.md
      - Raft: ds/raft.md
  - CTF:
    - ctf/prototype_pollution.md
  - Slides:
      - "🔗beautiful sequence": https://courses.zjusec.com/slides/beautiful_sequence/
